-- Shopping carts table for Club de Ofertas e-commerce system
create table public.carts_clubofertas (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null default now(),

    -- Cart identification
    cart_id text null unique,
    user_id bigint null,
    session_id text null,

    -- Cart status
    status text null default 'active' check (status in ('active', 'abandoned', 'converted', 'expired')),

    -- Cart totals (calculated)
    items_count integer null default 0,
    subtotal numeric(10,2) null default 0,
    total_amount numeric(10,2) null default 0,

    -- Metadata
    expires_at timestamp with time zone null,
    converted_at timestamp with time zone null,
    app text null default 'ecommerce'::text,

    constraint carts_clubofertas_pkey primary key (id),
    constraint carts_clubofertas_cart_id_unique unique (cart_id),
    constraint carts_clubofertas_user_id_fkey foreign key (user_id) references public.users_clubofertas(id) on delete set null,
    constraint carts_clubofertas_status_check check (status in ('active', 'abandoned', 'converted', 'expired'))
) TABLESPACE pg_default;

-- Cart items table
create table public.cart_items_clubofertas (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null default now(),

    -- Relations
    cart_id bigint null not null,
    product_id bigint null not null,

    -- Item details
    product_name text null,
    product_price numeric(10,2) null,
    quantity integer null default 1,

    -- Calculated fields
    item_total numeric(10,2) null generated always as (product_price * quantity) stored,

    -- Metadata
    added_at timestamp with time zone null default now(),
    app text null default 'ecommerce'::text,

    constraint cart_items_clubofertas_pkey primary key (id),
    constraint cart_items_clubofertas_cart_id_fkey foreign key (cart_id) references public.carts_clubofertas(id) on delete cascade,
    constraint cart_items_clubofertas_product_id_fkey foreign key (product_id) references public.products_clubofertas(id) on delete cascade,
    constraint cart_items_clubofertas_quantity_check check (quantity > 0)
) TABLESPACE pg_default;

-- Indexes for performance
create index idx_carts_clubofertas_user_id on public.carts_clubofertas (user_id);
create index idx_carts_clubofertas_session_id on public.carts_clubofertas (session_id);
create index idx_carts_clubofertas_status on public.carts_clubofertas (status);
create index idx_carts_clubofertas_app on public.carts_clubofertas (app);
create index idx_cart_items_clubofertas_cart_id on public.cart_items_clubofertas (cart_id);
create index idx_cart_items_clubofertas_product_id on public.cart_items_clubofertas (product_id);

-- Comments for documentation
comment on table public.carts_clubofertas is 'Shopping carts for Club de Ofertas e-commerce system';
comment on table public.cart_items_clubofertas is 'Individual items within shopping carts';
comment on column public.carts_clubofertas.cart_id is 'Unique identifier for cart that can be shared across sessions';
comment on column public.carts_clubofertas.session_id is 'Session identifier for guest users';
comment on column public.carts_clubofertas.status is 'Cart lifecycle status: active, abandoned, converted to order, or expired';