create table public.chats_clubofertas (
                              id bigint generated by default as identity not null,
                              created_at timestamp with time zone not null default now(),
                              phone text null,
                              updated_at timestamp with time zone null default now(),
                              conversation_id text null,
                              app text null default 'delivery'::text,
                              constraint chats_clubofertas_pkey primary key (id)
) TABLESPACE pg_default;

