create table public.chat_messages_clubofertas (
                                      id bigint generated by default as identity not null,
                                      created_at timestamp with time zone not null default now(),
                                      user_id text null,
                                      bot_message text null,
                                      phone text null,
                                      user_name text null,
                                      user_message text null,
                                      conversation_id text null,
                                      message_type text null,
                                      active boolean null default true,
                                      app text null default 'delivery'::text,
                                      constraint chat_messages_clubofertas_pkey primary key (id)
) TABLESPACE pg_default;
