-- Orders table for Club de Ofertas e-commerce system
create table public.orders_clubofertas (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null default now(),

    -- Order identification
    order_number text null unique,
    checkout_id text null unique,
    user_id bigint null,
    cart_id bigint null,

    -- Customer information
    customer_name text null,
    customer_email text null,
    customer_phone text null,

    -- Shipping information
    shipping_address text null,
    shipping_city text null,
    shipping_country text null default 'Paraguay',
    shipping_postal_code text null,
    shipping_neighborhood text null,
    shipping_number text null,
    shipping_complement text null,

    -- Order details
    items_count integer null default 0,
    subtotal numeric(10,2) null default 0,
    shipping_cost numeric(10,2) null default 0,
    tax numeric(10,2) null default 0,
    total_amount numeric(10,2) null default 0,

    -- Payment information
    payment_method text null check (payment_method in ('CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'PAYPAL', 'MERCADO_PAGO', 'PIX', 'OTHER')),
    payment_status text null default 'pending' check (payment_status in ('pending', 'processing', 'paid', 'failed', 'cancelled', 'refunded')),
    payment_reference text null,
    paid_at timestamp with time zone null,

    -- Order status
    status text null default 'pending' check (status in ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')),

    -- Additional information
    notes text null,
    internal_notes text null,
    tracking_number text null,
    estimated_delivery date,

    -- Timestamps
    confirmed_at timestamp with time zone null,
    processed_at timestamp with time zone null,
    shipped_at timestamp with time zone null,
    delivered_at timestamp with time zone null,
    cancelled_at timestamp with time zone null,

    -- Metadata
    app text null default 'ecommerce'::text,
    source text null default 'whatsapp',

    constraint orders_clubofertas_pkey primary key (id),
    constraint orders_clubofertas_order_number_unique unique (order_number),
    constraint orders_clubofertas_checkout_id_unique unique (checkout_id),
    constraint orders_clubofertas_user_id_fkey foreign key (user_id) references public.users_clubofertas(id) on delete set null,
    constraint orders_clubofertas_cart_id_fkey foreign key (cart_id) references public.carts_clubofertas(id) on delete set null,
    constraint orders_clubofertas_payment_method_check check (payment_method in ('CASH', 'CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'PAYPAL', 'MERCADO_PAGO', 'PIX', 'OTHER')),
    constraint orders_clubofertas_payment_status_check check (payment_status in ('pending', 'processing', 'paid', 'failed', 'cancelled', 'refunded')),
    constraint orders_clubofertas_status_check check (status in ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded'))
) TABLESPACE pg_default;

-- Order items table
create table public.order_items_clubofertas (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null default now(),

    -- Relations
    order_id bigint null not null,
    product_id bigint null not null,

    -- Product snapshot at time of purchase
    product_name text null,
    product_description text null,
    product_image text null,
    product_price numeric(10,2) null,
    product_category text null,
    product_brand text null,
    product_sku text null,

    -- Order item details
    quantity integer null default 1,
    unit_price numeric(10,2) null,
    item_total numeric(10,2) null generated always as (unit_price * quantity) stored,

    -- Status
    status text null default 'pending' check (status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', 'refunded')),

    -- Metadata
    app text null default 'ecommerce'::text,

    constraint order_items_clubofertas_pkey primary key (id),
    constraint order_items_clubofertas_order_id_fkey foreign key (order_id) references public.orders_clubofertas(id) on delete cascade,
    constraint order_items_clubofertas_product_id_fkey foreign key (product_id) references public.products_clubofertas(id) on delete restrict,
    constraint order_items_clubofertas_quantity_check check (quantity > 0),
    constraint order_items_clubofertas_status_check check (status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled', 'refunded'))
) TABLESPACE pg_default;

-- Order status history table
create table public.order_status_history_clubofertas (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),

    order_id bigint null not null,
    from_status text null,
    to_status text null not null,
    reason text null,
    notes text null,
    created_by bigint null, -- User ID who made the change

    constraint order_status_history_clubofertas_pkey primary key (id),
    constraint order_status_history_clubofertas_order_id_fkey foreign key (order_id) references public.orders_clubofertas(id) on delete cascade,
    constraint order_status_history_clubofertas_created_by_fkey foreign key (created_by) references public.users_clubofertas(id) on delete set null
) TABLESPACE pg_default;

-- Indexes for performance
create index idx_orders_clubofertas_user_id on public.orders_clubofertas (user_id);
create index idx_orders_clubofertas_status on public.orders_clubofertas (status);
create index idx_orders_clubofertas_payment_status on public.orders_clubofertas (payment_status);
create index idx_orders_clubofertas_created_at on public.orders_clubofertas (created_at);
create index idx_orders_clubofertas_order_number on public.orders_clubofertas (order_number);
create index idx_orders_clubofertas_app on public.orders_clubofertas (app);
create index idx_order_items_clubofertas_order_id on public.order_items_clubofertas (order_id);
create index idx_order_items_clubofertas_product_id on public.order_items_clubofertas (product_id);
create index idx_order_status_history_clubofertas_order_id on public.order_status_history_clubofertas (order_id);

-- Comments for documentation
comment on table public.orders_clubofertas is 'Main orders table for Club de Ofertas e-commerce system';
comment on table public.order_items_clubofertas is 'Individual items within orders with product snapshot';
comment on table public.order_status_history_clubofertas is 'Audit trail for order status changes';
comment on column public.orders_clubofertas.order_number is 'Human-readable order number for customer reference';
comment on column public.orders_clubofertas.checkout_id is 'Unique checkout session identifier';
comment on column public.orders_clubofertas.payment_reference is 'Payment gateway transaction ID';
comment on column public.orders_clubofertas.source is 'Where the order originated (whatsapp, web, mobile, etc.)';
comment on column public.order_items_clubofertas.product_name is 'Snapshot of product name at time of purchase';
comment on column public.order_items_clubofertas.product_price is 'Snapshot of product price at time of purchase';