create table public.products_clubofertas (
                                 id bigint generated by default as identity not null,
                                 created_at timestamp with time zone not null default now(),
                                 title text null,
                                 price text null,
                                 foto text null,
                                 description text null,
                                 in_stock boolean null default true,
                                 size text null default 'M'::text,
                                 cor text null,
                                 categoria text null,
                                 video text null,
                                 youtube_video text null,
                                 marca text null,
                                 constraint products_clubofertas_pkey primary key (id)
) TABLESPACE pg_default;
