create table public.purchase_clubofertas (
                                 id bigint generated by default as identity not null,
                                 created_at timestamp with time zone not null default now(),
                                 value text not null,
                                 pay boolean not null default false,
                                 qrcode text null,
                                 description text null,
                                 "invoiceNumber" text null,
                                 phone text null,
                                 url_qrcode text null,
                                 constraint purchase_clubofertas_pkey primary key (id)
) TABLESPACE pg_default;
