-- Users table for Club de Ofertas e-commerce system
create table public.users_clubofertas (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null default now(),

    -- Authentication fields
    username text null unique,
    email text null unique,
    phone text null unique,
    password_hash text null,

    -- Profile information
    first_name text null,
    last_name text null,
    full_name text null generated always as (coalesce(first_name, '') || ' ' || coalesce(last_name, '')) stored,

    -- Address information
    address text null,
    city text null,
    postal_code text null,
    country text null default 'Paraguay',
    neighborhood text null,
    street_number text null,
    address_complement text null,

    -- Geolocation
    latitude text null,
    longitude text null,

    -- Account status
    is_active boolean null default true,
    is_verified boolean null default false,
    email_verified_at timestamp with time zone null,
    phone_verified_at timestamp with time zone null,

    -- Metadata
    last_login_at timestamp with time zone null,
    registration_source text null default 'whatsapp',
    app text null default 'ecommerce'::text,

    constraint users_clubofertas_pkey primary key (id),
    constraint users_clubofertas_username_unique unique (username),
    constraint users_clubofertas_email_unique unique (email),
    constraint users_clubofertas_phone_unique unique (phone)
) TABLESPACE pg_default;

-- Indexes for performance
create index idx_users_clubofertas_email on public.users_clubofertas (email);
create index idx_users_clubofertas_phone on public.users_clubofertas (phone);
create index idx_users_clubofertas_active on public.users_clubofertas (is_active);
create index idx_users_clubofertas_app on public.users_clubofertas (app);

-- Comments for documentation
comment on table public.users_clubofertas is 'Users table for Club de Ofertas e-commerce system with authentication and profile information';
comment on column public.users_clubofertas.registration_source is 'Source where user registered (whatsapp, web, mobile, etc.)';
comment on column public.users_clubofertas.app is 'Application identifier (ecommerce, delivery, etc.)';