-- =========================================
-- Experience Club - n8n Chatbot Database Schema
-- =========================================
-- This schema creates tables for storing chatbot conversations and analytics
-- Compatible with PostgreSQL 12+

-- Drop existing tables (if recreating)
-- DROP TABLE IF EXISTS analytics CASCADE;
-- DROP TABLE IF EXISTS conversations CASCADE;

-- =========================================
-- Table: conversations
-- Stores all chat messages between users and bot
-- =========================================
CREATE TABLE IF NOT EXISTS conversations (
    id SERIAL PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL DEFAULT 'anonymous',
    user_message TEXT NOT NULL,
    bot_response TEXT,
    response_id VARCHAR(255),
    context JSONB,
    page VARCHAR(500),
    user_agent TEXT,
    suggestions JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_conversations_session_id ON conversations(session_id);
CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations(user_id);
CREATE INDEX IF NOT EXISTS idx_conversations_created_at ON conversations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_session_created ON conversations(session_id, created_at DESC);

-- Add comments for documentation
COMMENT ON TABLE conversations IS 'Stores all chatbot conversation messages with context';
COMMENT ON COLUMN conversations.session_id IS 'Unique session identifier for tracking conversations';
COMMENT ON COLUMN conversations.user_id IS 'User identifier (from auth or anonymous)';
COMMENT ON COLUMN conversations.user_message IS 'Message sent by the user';
COMMENT ON COLUMN conversations.bot_response IS 'Response generated by the bot';
COMMENT ON COLUMN conversations.response_id IS 'Unique identifier for bot response';
COMMENT ON COLUMN conversations.context IS 'JSON context data (page, user agent, etc.)';
COMMENT ON COLUMN conversations.suggestions IS 'Quick reply suggestions shown to user';

-- =========================================
-- Table: analytics
-- Stores analytics data for chatbot performance
-- =========================================
CREATE TABLE IF NOT EXISTS analytics (
    id SERIAL PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL DEFAULT 'anonymous',
    intent VARCHAR(100),
    response_time_ms INTEGER,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    page VARCHAR(500),
    user_satisfied BOOLEAN,
    feedback_comment TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for analytics queries
CREATE INDEX IF NOT EXISTS idx_analytics_session_id ON analytics(session_id);
CREATE INDEX IF NOT EXISTS idx_analytics_intent ON analytics(intent);
CREATE INDEX IF NOT EXISTS idx_analytics_timestamp ON analytics(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_user_id ON analytics(user_id);

-- Add comments for documentation
COMMENT ON TABLE analytics IS 'Stores chatbot performance analytics and metrics';
COMMENT ON COLUMN analytics.intent IS 'Detected user intent (greeting, pricing, shipping, etc.)';
COMMENT ON COLUMN analytics.response_time_ms IS 'Time taken to generate response in milliseconds';
COMMENT ON COLUMN analytics.user_satisfied IS 'User satisfaction rating (true/false)';

-- =========================================
-- Optional: Conversation Statistics View
-- =========================================
CREATE OR REPLACE VIEW conversation_stats AS
SELECT
    DATE_TRUNC('day', created_at) as date,
    COUNT(DISTINCT session_id) as unique_sessions,
    COUNT(*) as total_messages,
    COUNT(DISTINCT user_id) as unique_users,
    AVG(CASE
        WHEN bot_response IS NOT NULL THEN
            EXTRACT(EPOCH FROM (updated_at - created_at)) * 1000
        END) as avg_response_time_ms
FROM conversations
GROUP BY DATE_TRUNC('day', created_at)
ORDER BY date DESC;

COMMENT ON VIEW conversation_stats IS 'Daily statistics for chatbot conversations';

-- =========================================
-- Optional: Intent Analytics View
-- =========================================
CREATE OR REPLACE VIEW intent_analytics AS
SELECT
    intent,
    COUNT(*) as total_count,
    AVG(response_time_ms) as avg_response_time,
    COUNT(DISTINCT session_id) as unique_sessions,
    COUNT(CASE WHEN user_satisfied = true THEN 1 END) as satisfied_count,
    COUNT(CASE WHEN user_satisfied = false THEN 1 END) as unsatisfied_count
FROM analytics
WHERE created_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY intent
ORDER BY total_count DESC;

COMMENT ON VIEW intent_analytics IS 'Analytics grouped by intent for last 30 days';

-- =========================================
-- Function: Clean old conversations (optional)
-- =========================================
CREATE OR REPLACE FUNCTION cleanup_old_conversations(days_to_keep INTEGER DEFAULT 90)
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER;
BEGIN
    DELETE FROM conversations
    WHERE created_at < CURRENT_DATE - (days_to_keep || ' days')::INTERVAL;

    GET DIAGNOSTICS deleted_count = ROW_COUNT;

    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION cleanup_old_conversations IS 'Deletes conversations older than specified days (default 90)';

-- =========================================
-- Trigger: Update updated_at timestamp
-- =========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_conversations_updated_at
    BEFORE UPDATE ON conversations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =========================================
-- Grant permissions (adjust as needed)
-- =========================================
-- GRANT SELECT, INSERT, UPDATE ON conversations TO n8n_user;
-- GRANT SELECT, INSERT ON analytics TO n8n_user;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO n8n_user;

-- =========================================
-- Insert sample data for testing (optional)
-- =========================================
/*
INSERT INTO conversations (session_id, user_id, user_message, bot_response, context, page)
VALUES
    ('test_session_1', 'user_123', 'Hola', '¡Hola! Bienvenido a Experience Club. ¿En qué puedo ayudarte?',
     '{"userAgent": "Mozilla/5.0", "page": "/"}', '/'),
    ('test_session_1', 'user_123', '¿Cuánto cuesta el envío?', 'El envío cuesta ₲43.770 y es GRATIS en compras mayores a ₲730.000',
     '{"userAgent": "Mozilla/5.0", "page": "/"}', '/');

INSERT INTO analytics (session_id, user_id, intent, response_time_ms)
VALUES
    ('test_session_1', 'user_123', 'greeting', 150),
    ('test_session_1', 'user_123', 'shipping', 230);
*/

-- =========================================
-- Verification Queries
-- =========================================
-- Check if tables were created successfully
SELECT
    table_name,
    (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name) as column_count
FROM information_schema.tables t
WHERE table_schema = 'public'
    AND table_name IN ('conversations', 'analytics')
ORDER BY table_name;

-- Show recent conversations
-- SELECT * FROM conversations ORDER BY created_at DESC LIMIT 10;

-- Show analytics summary
-- SELECT * FROM intent_analytics;

-- Show daily stats
-- SELECT * FROM conversation_stats ORDER BY date DESC LIMIT 7;
